### ISSUE TITLE
LHC-Forms download?

### ISSUE THREAD

**Issue by sumeetchhetri** [lhncbc/clin-table-search#6]
Can we download the LHC-Forms for the panel tests directly instead of relying on the (https://clinicaltables.nlm.nih.gov/) API service. This would be really helpful.

**Comment by plynchnlm** [comment]
If I understand your question, I think you asking whether the LHC-Forms form definitions for the LOINC panels can be downloaded.  You can certainly download them once and store your own copies.  Just be aware of the license (https://loinc.org/kb/license/) that goes along with LOINC.  If you are looking for a bulk download of all of them, we don't offer that.  However, we would encourage you to switch to using LOINC's FHIR Questionnaire form definitions rather than our LHC-Forms format, because FHIR Questionnaires are an HL7 standard, as opposed to a custom format.  LHC-Forms can also render FHIR Questionnaire definitions.  (See https://lhncbc.github.io/lforms/#fhirSupport for additional files to load for FHIR support.)    LOINC's FHIR Questionnaire definitions can be downloaded in bulk from their FHIR server, at https://fhir.loinc.org/Questionnaire, though you will need to sign up for a free account (https://loinc.org/join/).  When last I checked, there were some minor deficiencies in the Questionnaire definitions (e.g., missing help text, which they were working on fixing), but if they meet your needs it would be better to use those.

I hope that helps, and that I have not missed what you were asking.
