### ISSUE TITLE
Feature Request: Expose SXDG_RXCUI in response

### ISSUE THREAD

**Issue by WesleyKapow** [lhncbc/clin-table-search#9]
For more flexibility, it'd be nice to have the `SXDG_RXCUI` codes in the response. This way, we could allow selecting "Aspirin (Oral)" without specifying a strength and still get mapped to the RxNorm CUI of `1154070`. This can drastically improve patient onboarding as some patients may know the drug but not the dosage.

**Comment by xluanlhc** [comment]
Thanks for the message, we are looking into this.

**Comment by plynchnlm** [comment]
We can add this code as a optional field to retrieve, but it probably won't serve the purpose you have in mind, because there isn't a 1:1 correspondence between SXDG_RXCUI and the DISPLAY_NAME in RxTerms.  Example:  Both "Budesonide (Oral Pill)" and "Budesonide XR (Oral Pill)" have the same SXDG_RXCUI.  If you are looking for a code for DISPLAY_NAME, there isn't one.  In our own apps, we use the DISPLAY_NAME itself as the "code".

**Comment by WesleyKapow** [comment]
@plynchnlm For our use case, we don't need a one-to-one mapping from `DISPLAY_NAME` to `SXDG_RXCUI`. So, as per your example, it'd be ok that the user selected "Budesonide (Oral Pill)" and the RXCUI we got did not allow us to distinguish that selection from "Budesonide XR (Oral Pill)". We'd still like the RXCUI here so we can inform a clinician what non-specific drug this patient is taking.

Again this allows us to get some RXCUI when a patient does not select the strength. This allows us to set the strength field as optional and still get the RXCUI associated with the general medication they selected.

Also probably worth noting, we will likely be hosting our own RxTerm API, so this is not a pressing need but I thought it'd be a helpful improvement for others as well.

**Comment by plynchnlm** [comment]
Thanks for the suggestion.   We're planning to add it as an optional field, and I expect it will be available within 1-3 weeks.
